#ifndef __processes_dlg__
#define __processes_dlg__

/**
@file
Subclass of processes_dlg_base, which is generated by wxFormBuilder.
*/

#include "dc_gui.h"
#include "dcsettings.h"

//// end generated include

struct running_processes;

/** Implementing processes_dlg_base */
class processes_dlg : public processes_dlg_base
{
	// Hide constructor
	processes_dlg( wxWindow* parent );
	protected:
		// Handlers for processes_dlg_base events.
		void ok_btn_click( wxCommandEvent& event );

		void check_open_processes(running_processes& rp);
	public:
		/** Constructor */
		processes_dlg( wxWindow* parent, diskcleaner::global_& gbsettings );
	//// end generated class members

};

#endif // __processes_dlg__
