#ifndef __wait_dlg__
#define __wait_dlg__

/**
@file
Subclass of wait_base_dlg, which is generated by wxFormBuilder.
*/

#include "dc_gui.h"

/** Implementing wait_base_dlg */
class wait_dlg : public wait_base_dlg
{
public:
	/** Constructor */
	wait_dlg( wxWindow* parent );
	void SetProgressRange( const int maximum );
	void Increment( void );
};

#endif // __wait_dlg__
