/*
** Copyright (C) 2009 Robert Moerland
**
** This program is free software; you can redistribute it and/or modify
** it under the terms of the GNU General Public License as published by
** the Free Software Foundation version 2.
**
** This program is distributed in the hope that it will be useful,
** but WITHOUT ANY WARRANTY; without even the implied warranty of
** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
** GNU General Public License for more details.
**
** You should have received a copy of the GNU General Public License
** along with this program; if not, write to the Free Software
** Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
*/

#ifndef __about_frame__
#define __about_frame__

/**
@file
Subclass of about_base_dlg, which is generated by wxFormBuilder.
*/

#include "dc_gui.h"

/** Implementing about_base_dlg */
class about_frame : public about_base_dlg
{
protected:
	// Handlers for about_base_dlg events.
	void ok_btn_clicked( wxCommandEvent& event );

public:
	/** Constructor */
	about_frame( wxWindow* parent );
};

#endif // __about_frame__
